name: Code check

on: [push]

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python and dependencies
        uses: ./.github/actions/install
      - name: Run ruff and mypy
        run: |
          poetry run ruff check --output-format=github app
          poetry run mypy -p app
