name: Code check

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and dependencies
        uses: ./.github/actions/install
      - name: Run ruff and mypy
        run: poetry run ruff bot --format github
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and dependencies
        uses: ./.github/actions/install
      - name: Add mypy annotator
        uses: pr-annotators/mypy-pr-annotator@v1.0.0
      - name: Run mypy
        run: poetry run mypy -p bot
