name: Tests

on:
  push:
    paths:
      - ".github/workflows/tests.yml"
      - "app/**"
      - "tests/**"
      - "codecov.yaml"
      - "pyproject.toml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and dependencies
        uses: ./.github/actions/install
      - name: Run tests
        run: |
          poetry run pytest --cov app --cov-config .coveragerc --cov-report=xml
      - name: Upload coverage data
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests